/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CopilotRouteImport } from './routes/copilot'
import { Route as EstudioVisualRouteImport } from './routes/estudio-visual'
import { Route as ListaRouteImport } from './routes/lista'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as OportunidadesIdRouteImport } from './routes/oportunidades.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CopilotRoute = CopilotRouteImport.update({
  id: '/copilot',
  path: '/copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const EstudioVisualRoute = EstudioVisualRouteImport.update({
  id: '/estudio-visual',
  path: '/estudio-visual',
  getParentRoute: () => rootRouteImport,
} as any)
const ListaRoute = ListaRouteImport.update({
  id: '/lista',
  path: '/lista',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const OportunidadesIdRoute = OportunidadesIdRouteImport.update({
  id: '/oportunidades/$id',
  path: '/oportunidades/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/copilot': typeof CopilotRoute
  '/estudio-visual': typeof EstudioVisualRoute
  '/lista': typeof ListaRoute
  '/noticias': typeof NoticiasRoute
  '/usuarios': typeof UsuariosRoute
  '/oportunidades/$id': typeof OportunidadesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/copilot': typeof CopilotRoute
  '/estudio-visual': typeof EstudioVisualRoute
  '/lista': typeof ListaRoute
  '/noticias': typeof NoticiasRoute
  '/usuarios': typeof UsuariosRoute
  '/oportunidades/$id': typeof OportunidadesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/copilot': typeof CopilotRoute
  '/estudio-visual': typeof EstudioVisualRoute
  '/lista': typeof ListaRoute
  '/noticias': typeof NoticiasRoute
  '/usuarios': typeof UsuariosRoute
  '/oportunidades/$id': typeof OportunidadesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/copilot'
    | '/estudio-visual'
    | '/lista'
    | '/noticias'
    | '/usuarios'
    | '/oportunidades/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/copilot'
    | '/estudio-visual'
    | '/lista'
    | '/noticias'
    | '/usuarios'
    | '/oportunidades/$id'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/copilot'
    | '/estudio-visual'
    | '/lista'
    | '/noticias'
    | '/usuarios'
    | '/oportunidades/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  CopilotRoute: typeof CopilotRoute
  EstudioVisualRoute: typeof EstudioVisualRoute
  ListaRoute: typeof ListaRoute
  NoticiasRoute: typeof NoticiasRoute
  UsuariosRoute: typeof UsuariosRoute
  OportunidadesIdRoute: typeof OportunidadesIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copilot': {
      id: '/copilot'
      path: '/copilot'
      fullPath: '/copilot'
      preLoaderRoute: typeof CopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estudio-visual': {
      id: '/estudio-visual'
      path: '/estudio-visual'
      fullPath: '/estudio-visual'
      preLoaderRoute: typeof EstudioVisualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lista': {
      id: '/lista'
      path: '/lista'
      fullPath: '/lista'
      preLoaderRoute: typeof ListaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oportunidades/$id': {
      id: '/oportunidades/$id'
      path: '/oportunidades/$id'
      fullPath: '/oportunidades/$id'
      preLoaderRoute: typeof OportunidadesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  CopilotRoute: CopilotRoute,
  EstudioVisualRoute: EstudioVisualRoute,
  ListaRoute: ListaRoute,
  NoticiasRoute: NoticiasRoute,
  UsuariosRoute: UsuariosRoute,
  OportunidadesIdRoute: OportunidadesIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
